# Generated by Django 6.0.6 on 2026-07-08 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_allergies_user_blood_group_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_caregiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='caregiver_shift',
            field=models.CharField(blank=True, help_text='Time slot for the caregiver, e.g. Morning or Evening', max_length=30, null=True),
        ),
    ]
