# Generated by Django 6.0.6 on 2026-07-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_assigned_caregiver_user_caregiver_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='daily_confirmation_time',
            field=models.TimeField(blank=True, help_text='Time to send daily confirmation email (e.g., 09:00:00)', null=True),
        ),
    ]
