# Generated by Django 6.0.6 on 2026-07-22 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_daily_confirmation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='daily_confirmation_time',
        ),
    ]
