# Generated by Django 6.0.6 on 2026-07-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_notes_reminder_snooze_until_reminder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='initial_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
