# Generated by Django 6.0.6 on 2026-07-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='dose_times',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='schedule_type',
            field=models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=20, null=True),
        ),
    ]
