# Generated by Django 6.0.6 on 2026-07-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_medicine_dose_times_medicine_schedule_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='low_stock_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
